/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DestinationCreateNestedManyWithoutUsersInput } from "./DestinationCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { PacientCreateNestedManyWithoutUsersInput } from "./PacientCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => DestinationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DestinationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DestinationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  destinations?: DestinationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => PacientCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PacientCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PacientCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  pacients?: PacientCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
